// <auto-generated />
using System;
using GamefiedSelfImprovement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gamified_Self_Improvement.Migrations
{
    [DbContext(typeof(GamefiedSelfImprovementDbContext))]
    [Migration("20260430090742_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GamefiedSelfImprovement.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityType")
                        .HasColumnType("int")
                        .HasJsonPropertyName("activityType");

                    b.Property<DateTime>("CompletedDate")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("completedDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("description");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int")
                        .HasJsonPropertyName("difficulty");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("userId");

                    b.Property<int>("XpReward")
                        .HasColumnType("int")
                        .HasJsonPropertyName("xpReward");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Activity");

                    b
                        .UseTphMappingStrategy()
                        .HasAnnotation("Relational:JsonPropertyName", "activities");
                });

            modelBuilder.Entity("GamefiedSelfImprovement.SpiritualBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("author");

                    b.Property<int>("BookType")
                        .HasColumnType("int")
                        .HasJsonPropertyName("bookType");

                    b.PrimitiveCollection<string>("Chapters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("chapters");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("description");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit")
                        .HasJsonPropertyName("isAvailable");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("language");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("title");

                    b.Property<int>("TotalPages")
                        .HasColumnType("int")
                        .HasJsonPropertyName("totalPages");

                    b.HasKey("Id");

                    b.ToTable("SpiritualBooks");

                    b.HasAnnotation("Relational:JsonPropertyName", "book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Razni autori",
                            BookType = 0,
                            Chapters = "[]",
                            Description = "Kršćanski sveti tekst",
                            IsAvailable = true,
                            Language = "Croatian",
                            Title = "Biblija (Novi zavjet)",
                            TotalPages = 260
                        },
                        new
                        {
                            Id = 2,
                            Author = "Prorok Muhammad (Mir budi s njim)",
                            BookType = 1,
                            Chapters = "[]",
                            Description = "Islamski sveti tekst",
                            IsAvailable = true,
                            Language = "Croatian",
                            Title = "Kuran",
                            TotalPages = 604
                        },
                        new
                        {
                            Id = 3,
                            Author = "Mojsije i drugi",
                            BookType = 2,
                            Chapters = "[]",
                            Description = "Židovski sveti tekst",
                            IsAvailable = true,
                            Language = "Croatian",
                            Title = "Tora",
                            TotalPages = 187
                        });
                });

            modelBuilder.Entity("GamefiedSelfImprovement.TrainingLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Difficulty")
                        .HasColumnType("int")
                        .HasJsonPropertyName("difficulty");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("exerciseId");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("exerciseName");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("logDate");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("notes");

                    b.Property<int>("Reps")
                        .HasColumnType("int")
                        .HasJsonPropertyName("reps");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("int")
                        .HasJsonPropertyName("restSeconds");

                    b.Property<int>("Sets")
                        .HasColumnType("int")
                        .HasJsonPropertyName("sets");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("userId");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)")
                        .HasJsonPropertyName("weight");

                    b.HasKey("Id");

                    b.ToTable("TrainingLogs");
                });

            modelBuilder.Entity("GamefiedSelfImprovement.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("bio");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("createdDate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("email");

                    b.PrimitiveCollection<string>("FavoriteBooks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("favoriteBooks");

                    b.Property<DateTime>("LastActiveDate")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("lastActiveDate");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasJsonPropertyName("level");

                    b.Property<int>("PreferredMeditationType")
                        .HasColumnType("int")
                        .HasJsonPropertyName("preferredMeditationType");

                    b.Property<string>("ProfileImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("profileImagePath");

                    b.Property<int>("StreakDays")
                        .HasColumnType("int")
                        .HasJsonPropertyName("streakDays");

                    b.Property<int>("TotalXP")
                        .HasColumnType("int")
                        .HasJsonPropertyName("totalXP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GamefiedSelfImprovement.XPReward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityType")
                        .HasColumnType("int")
                        .HasJsonPropertyName("activityType");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("name");

                    b.Property<DateTime>("UnlockedDate")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("unlockedDate");

                    b.Property<int>("XpAmount")
                        .HasColumnType("int")
                        .HasJsonPropertyName("xpAmount");

                    b.HasKey("Id");

                    b.ToTable("XPRewards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityType = 0,
                            Description = "",
                            Icon = "💪",
                            Name = "Početni trening",
                            UnlockedDate = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            XpAmount = 50
                        },
                        new
                        {
                            Id = 2,
                            ActivityType = 2,
                            Description = "",
                            Icon = "🧘",
                            Name = "Dnevna meditacija",
                            UnlockedDate = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            XpAmount = 30
                        },
                        new
                        {
                            Id = 3,
                            ActivityType = 1,
                            Description = "",
                            Icon = "📖",
                            Name = "Čitanje duhovnog teksta",
                            UnlockedDate = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            XpAmount = 40
                        },
                        new
                        {
                            Id = 4,
                            ActivityType = 3,
                            Description = "",
                            Icon = "📝",
                            Name = "Refleksija u dnevniku",
                            UnlockedDate = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            XpAmount = 25
                        });
                });

            modelBuilder.Entity("GamefiedSelfImprovement.DailyJournal", b =>
                {
                    b.HasBaseType("GamefiedSelfImprovement.Activity");

                    b.PrimitiveCollection<string>("Accomplishments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("accomplishments");

                    b.PrimitiveCollection<string>("Ambitions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("ambitions");

                    b.PrimitiveCollection<string>("Challenges")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("challenges");

                    b.PrimitiveCollection<string>("DailyGoals")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("dailyGoals");

                    b.Property<int>("EnergyLevel")
                        .HasColumnType("int")
                        .HasJsonPropertyName("energyLevel");

                    b.Property<DateTime>("JournalDate")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("journalDate");

                    b.Property<int>("Mood")
                        .HasColumnType("int")
                        .HasJsonPropertyName("mood");

                    b.Property<string>("Reflection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("reflection");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasIndex("UserId1");

                    b.HasDiscriminator().HasValue("DailyJournal");

                    b.HasAnnotation("Relational:JsonPropertyName", "journals");
                });

            modelBuilder.Entity("GamefiedSelfImprovement.Exercise", b =>
                {
                    b.HasBaseType("GamefiedSelfImprovement.Activity");

                    b.Property<int>("CaloriesBurned")
                        .HasColumnType("int")
                        .HasJsonPropertyName("caloriesBurned");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int")
                        .HasJsonPropertyName("durationMinutes");

                    b.Property<int>("ExerciseType")
                        .HasColumnType("int")
                        .HasJsonPropertyName("exerciseType");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("location");

                    b.PrimitiveCollection<string>("MuscleGroups")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("muscleGroups");

                    b.Property<int>("Reps")
                        .HasColumnType("int")
                        .HasJsonPropertyName("reps");

                    b.Property<int>("Sets")
                        .HasColumnType("int")
                        .HasJsonPropertyName("sets");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)")
                        .HasJsonPropertyName("weight");

                    b.HasDiscriminator().HasValue("Exercise");
                });

            modelBuilder.Entity("GamefiedSelfImprovement.Meditation", b =>
                {
                    b.HasBaseType("GamefiedSelfImprovement.Activity");

                    b.Property<string>("AudioFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("audioFilePath");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int")
                        .HasJsonPropertyName("durationMinutes");

                    b.Property<string>("FocusArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("focusArea");

                    b.Property<int>("MeditationType")
                        .HasColumnType("int")
                        .HasJsonPropertyName("meditationType");

                    b.Property<int>("MentalClarity")
                        .HasColumnType("int")
                        .HasJsonPropertyName("mentalClarity");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("notes");

                    b.Property<int>("StressReliefScore")
                        .HasColumnType("int")
                        .HasJsonPropertyName("stressReliefScore");

                    b.ToTable("Activities", t =>
                        {
                            t.Property("DurationMinutes")
                                .HasColumnName("Meditation_DurationMinutes");
                        });

                    b.HasDiscriminator().HasValue("Meditation");
                });

            modelBuilder.Entity("GamefiedSelfImprovement.SpiritualActivity", b =>
                {
                    b.HasBaseType("GamefiedSelfImprovement.Activity");

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("bookId");

                    b.Property<int>("CurrentPage")
                        .HasColumnType("int")
                        .HasJsonPropertyName("currentPage");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int")
                        .HasJsonPropertyName("durationMinutes");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit")
                        .HasJsonPropertyName("isCompleted");

                    b.Property<int>("PagesRead")
                        .HasColumnType("int")
                        .HasJsonPropertyName("pagesRead");

                    b.Property<string>("Reflection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("reflection");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("startDate");

                    b.HasIndex("BookId");

                    b.ToTable("Activities", t =>
                        {
                            t.Property("DurationMinutes")
                                .HasColumnName("SpiritualActivity_DurationMinutes");

                            t.Property("Reflection")
                                .HasColumnName("SpiritualActivity_Reflection");
                        });

                    b.HasDiscriminator().HasValue("SpiritualActivity");
                });

            modelBuilder.Entity("GamefiedSelfImprovement.Activity", b =>
                {
                    b.HasOne("GamefiedSelfImprovement.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamefiedSelfImprovement.DailyJournal", b =>
                {
                    b.HasOne("GamefiedSelfImprovement.User", null)
                        .WithMany("Journals")
                        .HasForeignKey("UserId1");
                });

            modelBuilder.Entity("GamefiedSelfImprovement.SpiritualActivity", b =>
                {
                    b.HasOne("GamefiedSelfImprovement.SpiritualBook", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("GamefiedSelfImprovement.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Journals");
                });
#pragma warning restore 612, 618
        }
    }
}
