// <auto-generated />
using System;
using GamefiedSelfImprovement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gamified_Self_Improvement.Migrations
{
    [DbContext(typeof(GamefiedSelfImprovementDbContext))]
    [Migration("20260526091703_AddIdentityAndAttachments")]
    partial class AddIdentityAndAttachments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GamefiedSelfImprovement.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityType")
                        .HasColumnType("int")
                        .HasJsonPropertyName("activityType");

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasJsonPropertyName("appUserId");

                    b.Property<DateTime>("CompletedDate")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("completedDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasJsonPropertyName("description");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int")
                        .HasJsonPropertyName("difficulty");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasJsonPropertyName("title");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("userId");

                    b.Property<int>("XpReward")
                        .HasColumnType("int")
                        .HasJsonPropertyName("xpReward");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Activity");

                    b
                        .UseTphMappingStrategy()
                        .HasAnnotation("Relational:JsonPropertyName", "activity");
                });

            modelBuilder.Entity("GamefiedSelfImprovement.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasJsonPropertyName("bio");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("createdDate");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.PrimitiveCollection<string>("FavoriteBooks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("favoriteBooks");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasJsonPropertyName("jmbg");

                    b.Property<DateTime>("LastActiveDate")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("lastActiveDate");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasJsonPropertyName("level");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OIB")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasJsonPropertyName("oib");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("PreferredMeditationType")
                        .HasColumnType("int")
                        .HasJsonPropertyName("preferredMeditationType");

                    b.Property<string>("ProfileImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("profileImagePath");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StreakDays")
                        .HasColumnType("int")
                        .HasJsonPropertyName("streakDays");

                    b.Property<int>("TotalXP")
                        .HasColumnType("int")
                        .HasJsonPropertyName("totalXP");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "user");
                });

            modelBuilder.Entity("GamefiedSelfImprovement.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("activityId");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasJsonPropertyName("contentType");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasJsonPropertyName("description");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasJsonPropertyName("fileName");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("filePath");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("fileSize");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasJsonPropertyName("isDeleted");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("uploadedDate");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasJsonPropertyName("userId");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("UserId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("GamefiedSelfImprovement.SpiritualBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("author");

                    b.Property<int>("BookType")
                        .HasColumnType("int")
                        .HasJsonPropertyName("bookType");

                    b.PrimitiveCollection<string>("Chapters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("chapters");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("description");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit")
                        .HasJsonPropertyName("isAvailable");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("language");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("title");

                    b.Property<int>("TotalPages")
                        .HasColumnType("int")
                        .HasJsonPropertyName("totalPages");

                    b.HasKey("Id");

                    b.ToTable("SpiritualBooks");

                    b.HasAnnotation("Relational:JsonPropertyName", "book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Razni autori",
                            BookType = 0,
                            Chapters = "[]",
                            Description = "Kršćanski sveti tekst",
                            IsAvailable = true,
                            Language = "Croatian",
                            Title = "Biblija (Novi zavjet)",
                            TotalPages = 260
                        },
                        new
                        {
                            Id = 2,
                            Author = "Prorok Muhammad (Mir budi s njim)",
                            BookType = 1,
                            Chapters = "[]",
                            Description = "Islamski sveti tekst",
                            IsAvailable = true,
                            Language = "Croatian",
                            Title = "Kuran",
                            TotalPages = 604
                        },
                        new
                        {
                            Id = 3,
                            Author = "Mojsije i drugi",
                            BookType = 2,
                            Chapters = "[]",
                            Description = "Židovski sveti tekst",
                            IsAvailable = true,
                            Language = "Croatian",
                            Title = "Tora",
                            TotalPages = 187
                        });
                });

            modelBuilder.Entity("GamefiedSelfImprovement.TrainingLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Difficulty")
                        .HasColumnType("int")
                        .HasJsonPropertyName("difficulty");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("exerciseId");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("exerciseName");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("logDate");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("notes");

                    b.Property<int>("Reps")
                        .HasColumnType("int")
                        .HasJsonPropertyName("reps");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("int")
                        .HasJsonPropertyName("restSeconds");

                    b.Property<int>("Sets")
                        .HasColumnType("int")
                        .HasJsonPropertyName("sets");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("userId");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)")
                        .HasJsonPropertyName("weight");

                    b.HasKey("Id");

                    b.ToTable("TrainingLogs");
                });

            modelBuilder.Entity("GamefiedSelfImprovement.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasJsonPropertyName("bio");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("createdDate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("email");

                    b.PrimitiveCollection<string>("FavoriteBooks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("favoriteBooks");

                    b.Property<DateTime>("LastActiveDate")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("lastActiveDate");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasJsonPropertyName("level");

                    b.Property<int>("PreferredMeditationType")
                        .HasColumnType("int")
                        .HasJsonPropertyName("preferredMeditationType");

                    b.Property<string>("ProfileImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("profileImagePath");

                    b.Property<int>("StreakDays")
                        .HasColumnType("int")
                        .HasJsonPropertyName("streakDays");

                    b.Property<int>("TotalXP")
                        .HasColumnType("int")
                        .HasJsonPropertyName("totalXP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasJsonPropertyName("username");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "",
                            CreatedDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ivan@example.com",
                            FavoriteBooks = "[]",
                            LastActiveDate = new DateTime(2026, 5, 26, 11, 17, 2, 345, DateTimeKind.Local).AddTicks(9258),
                            Level = 5,
                            PreferredMeditationType = 3,
                            ProfileImagePath = "",
                            StreakDays = 0,
                            TotalXP = 850,
                            Username = "ivan_temuhin"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "",
                            CreatedDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marija@example.com",
                            FavoriteBooks = "[]",
                            LastActiveDate = new DateTime(2026, 5, 26, 11, 17, 2, 346, DateTimeKind.Local).AddTicks(2483),
                            Level = 3,
                            PreferredMeditationType = 1,
                            ProfileImagePath = "",
                            StreakDays = 0,
                            TotalXP = 420,
                            Username = "marija_fitness"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "",
                            CreatedDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "petar@example.com",
                            FavoriteBooks = "[]",
                            LastActiveDate = new DateTime(2026, 5, 26, 11, 17, 2, 346, DateTimeKind.Local).AddTicks(2489),
                            Level = 7,
                            PreferredMeditationType = 4,
                            ProfileImagePath = "",
                            StreakDays = 0,
                            TotalXP = 1200,
                            Username = "petar_spiritual"
                        });
                });

            modelBuilder.Entity("GamefiedSelfImprovement.XPReward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityType")
                        .HasColumnType("int")
                        .HasJsonPropertyName("activityType");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("name");

                    b.Property<DateTime>("UnlockedDate")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("unlockedDate");

                    b.Property<int>("XpAmount")
                        .HasColumnType("int")
                        .HasJsonPropertyName("xpAmount");

                    b.HasKey("Id");

                    b.ToTable("XPRewards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityType = 0,
                            Description = "",
                            Icon = "💪",
                            Name = "Početni trening",
                            UnlockedDate = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            XpAmount = 50
                        },
                        new
                        {
                            Id = 2,
                            ActivityType = 2,
                            Description = "",
                            Icon = "🧘",
                            Name = "Dnevna meditacija",
                            UnlockedDate = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            XpAmount = 30
                        },
                        new
                        {
                            Id = 3,
                            ActivityType = 1,
                            Description = "",
                            Icon = "📖",
                            Name = "Čitanje duhovnog teksta",
                            UnlockedDate = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            XpAmount = 40
                        },
                        new
                        {
                            Id = 4,
                            ActivityType = 3,
                            Description = "",
                            Icon = "📝",
                            Name = "Refleksija u dnevniku",
                            UnlockedDate = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            XpAmount = 25
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GamefiedSelfImprovement.DailyJournal", b =>
                {
                    b.HasBaseType("GamefiedSelfImprovement.Activity");

                    b.PrimitiveCollection<string>("Accomplishments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("accomplishments");

                    b.PrimitiveCollection<string>("Ambitions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("ambitions");

                    b.Property<string>("AppUserId1")
                        .HasColumnType("nvarchar(450)");

                    b.PrimitiveCollection<string>("Challenges")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("challenges");

                    b.PrimitiveCollection<string>("DailyGoals")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("dailyGoals");

                    b.Property<int>("EnergyLevel")
                        .HasColumnType("int")
                        .HasJsonPropertyName("energyLevel");

                    b.Property<DateTime>("JournalDate")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("journalDate");

                    b.Property<int>("Mood")
                        .HasColumnType("int")
                        .HasJsonPropertyName("mood");

                    b.Property<string>("Reflection")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasJsonPropertyName("reflection");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasIndex("AppUserId1");

                    b.HasIndex("UserId1");

                    b.HasDiscriminator().HasValue("DailyJournal");

                    b.HasAnnotation("Relational:JsonPropertyName", "journals");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            ActivityType = 3,
                            CompletedDate = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Razmišljanja o napretku",
                            Difficulty = 1,
                            Title = "Dnevna refleksija",
                            UserId = 3,
                            XpReward = 0,
                            Accomplishments = "[]",
                            Ambitions = "[]",
                            Challenges = "[]",
                            DailyGoals = "[]",
                            EnergyLevel = 8,
                            JournalDate = new DateTime(2026, 5, 26, 11, 17, 2, 349, DateTimeKind.Local).AddTicks(3436),
                            Mood = 8,
                            Reflection = ""
                        });
                });

            modelBuilder.Entity("GamefiedSelfImprovement.Exercise", b =>
                {
                    b.HasBaseType("GamefiedSelfImprovement.Activity");

                    b.Property<int>("CaloriesBurned")
                        .HasColumnType("int")
                        .HasJsonPropertyName("caloriesBurned");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int")
                        .HasJsonPropertyName("durationMinutes");

                    b.Property<int>("ExerciseType")
                        .HasColumnType("int")
                        .HasJsonPropertyName("exerciseType");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasJsonPropertyName("location");

                    b.PrimitiveCollection<string>("MuscleGroups")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("muscleGroups");

                    b.Property<int>("Reps")
                        .HasColumnType("int")
                        .HasJsonPropertyName("reps");

                    b.Property<int>("Sets")
                        .HasColumnType("int")
                        .HasJsonPropertyName("sets");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)")
                        .HasJsonPropertyName("weight");

                    b.HasDiscriminator().HasValue("Exercise");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityType = 0,
                            CompletedDate = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "5 km trčanja",
                            Difficulty = 1,
                            Title = "Trčanje ujutro",
                            UserId = 1,
                            XpReward = 0,
                            CaloriesBurned = 0,
                            DurationMinutes = 30,
                            ExerciseType = 1,
                            Location = "Kuća",
                            MuscleGroups = "[]",
                            Reps = 0,
                            Sets = 0,
                            Weight = 0m
                        },
                        new
                        {
                            Id = 2,
                            ActivityType = 0,
                            CompletedDate = new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Snaga - gornji dio tijela",
                            Difficulty = 1,
                            Title = "Vježbanje u teretani",
                            UserId = 1,
                            XpReward = 0,
                            CaloriesBurned = 0,
                            DurationMinutes = 45,
                            ExerciseType = 0,
                            Location = "Kuća",
                            MuscleGroups = "[]",
                            Reps = 10,
                            Sets = 3,
                            Weight = 20m
                        });
                });

            modelBuilder.Entity("GamefiedSelfImprovement.Meditation", b =>
                {
                    b.HasBaseType("GamefiedSelfImprovement.Activity");

                    b.Property<string>("AudioFilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasJsonPropertyName("audioFilePath");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int")
                        .HasJsonPropertyName("durationMinutes");

                    b.Property<string>("FocusArea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasJsonPropertyName("focusArea");

                    b.Property<int>("MeditationType")
                        .HasColumnType("int")
                        .HasJsonPropertyName("meditationType");

                    b.Property<int>("MentalClarity")
                        .HasColumnType("int")
                        .HasJsonPropertyName("mentalClarity");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasJsonPropertyName("notes");

                    b.Property<int>("StressReliefScore")
                        .HasColumnType("int")
                        .HasJsonPropertyName("stressReliefScore");

                    b.ToTable("Activities", t =>
                        {
                            t.Property("DurationMinutes")
                                .HasColumnName("Meditation_DurationMinutes");
                        });

                    b.HasDiscriminator().HasValue("Meditation");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            ActivityType = 2,
                            CompletedDate = new DateTime(2026, 5, 26, 11, 17, 2, 348, DateTimeKind.Local).AddTicks(9134),
                            Description = "10 minuta mindfulness meditacije",
                            Difficulty = 1,
                            Title = "Ujutna meditacija",
                            UserId = 2,
                            XpReward = 0,
                            AudioFilePath = "",
                            DurationMinutes = 10,
                            FocusArea = "Opća svjesnost",
                            MeditationType = 3,
                            MentalClarity = 7,
                            Notes = "",
                            StressReliefScore = 8
                        },
                        new
                        {
                            Id = 4,
                            ActivityType = 2,
                            CompletedDate = new DateTime(2026, 5, 26, 11, 17, 2, 349, DateTimeKind.Local).AddTicks(1676),
                            Description = "15 minuta dišanja",
                            Difficulty = 1,
                            Title = "Večernja meditacija",
                            UserId = 2,
                            XpReward = 0,
                            AudioFilePath = "",
                            DurationMinutes = 15,
                            FocusArea = "Opća svjesnost",
                            MeditationType = 1,
                            MentalClarity = 8,
                            Notes = "",
                            StressReliefScore = 9
                        });
                });

            modelBuilder.Entity("GamefiedSelfImprovement.SpiritualActivity", b =>
                {
                    b.HasBaseType("GamefiedSelfImprovement.Activity");

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasJsonPropertyName("bookId");

                    b.Property<int>("CurrentPage")
                        .HasColumnType("int")
                        .HasJsonPropertyName("currentPage");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int")
                        .HasJsonPropertyName("durationMinutes");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit")
                        .HasJsonPropertyName("isCompleted");

                    b.Property<int>("PagesRead")
                        .HasColumnType("int")
                        .HasJsonPropertyName("pagesRead");

                    b.Property<string>("Reflection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("reflection");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("startDate");

                    b.HasIndex("BookId");

                    b.ToTable("Activities", t =>
                        {
                            t.Property("DurationMinutes")
                                .HasColumnName("SpiritualActivity_DurationMinutes");

                            t.Property("Reflection")
                                .HasColumnName("SpiritualActivity_Reflection");
                        });

                    b.HasDiscriminator().HasValue("SpiritualActivity");
                });

            modelBuilder.Entity("GamefiedSelfImprovement.Activity", b =>
                {
                    b.HasOne("GamefiedSelfImprovement.AppUser", "AppUser")
                        .WithMany("Activities")
                        .HasForeignKey("AppUserId");

                    b.HasOne("GamefiedSelfImprovement.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId");

                    b.Navigation("AppUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamefiedSelfImprovement.Attachment", b =>
                {
                    b.HasOne("GamefiedSelfImprovement.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId");

                    b.HasOne("GamefiedSelfImprovement.AppUser", "User")
                        .WithMany("Attachments")
                        .HasForeignKey("UserId");

                    b.Navigation("Activity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GamefiedSelfImprovement.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GamefiedSelfImprovement.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamefiedSelfImprovement.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GamefiedSelfImprovement.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamefiedSelfImprovement.DailyJournal", b =>
                {
                    b.HasOne("GamefiedSelfImprovement.AppUser", null)
                        .WithMany("Journals")
                        .HasForeignKey("AppUserId1");

                    b.HasOne("GamefiedSelfImprovement.User", null)
                        .WithMany("Journals")
                        .HasForeignKey("UserId1");
                });

            modelBuilder.Entity("GamefiedSelfImprovement.SpiritualActivity", b =>
                {
                    b.HasOne("GamefiedSelfImprovement.SpiritualBook", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("GamefiedSelfImprovement.AppUser", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Attachments");

                    b.Navigation("Journals");
                });

            modelBuilder.Entity("GamefiedSelfImprovement.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Journals");
                });
#pragma warning restore 612, 618
        }
    }
}
